framework:
  default_locale: '%locale%'
  translator:
    default_path: '%kernel.project_dir%/ucgis_translations'
    fallbacks:
      - en
#    providers:
#      crowdin:
#        dsn: '%env(CROWDIN_DSN)%'
#      loco:
#        dsn: '%env(LOCO_DSN)%'
#      lokalise:
#        dsn: '%env(LOKALISE_DSN)%'
