services:
  ltb:
    build:
      context: .
      target: ltb_dev
      dockerfile: docker/ltb/Dockerfile
    restart: always
    volumes:
      - './:/usr/src/app/:z'
    environment:
      APP_ENV: dev
      PYTHON_PATH: '/usr/local/bin/python3.8'
      DATABASE_CHECK: 'db:3306'
      DATABASE_URL: 'mysql://ltb:%database_password%@db:3306/ltb'
      PRODUCTION_SERVER: 'false'
      TRUSTED_PROXIES: 10.9.8.1
      HTTP_HOST: 'localhost:10443'
    depends_on:
      - db
    networks:
      - ltb-network

  latex-server:
    build:
      context: docker/latex-server
      dockerfile: Containerfile
    image: nasumilu.io/latext-server:latest
    container_name: latex-server
    environment:
      APP_LOG_LEVEL: INFO
    networks:
      - ltb-network

  nginx:
    image: nginx:1.29.6-alpine
    restart: always
    volumes:
      - './:/usr/src/app:ro'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,z'
      - './docker/nginx/server.cert:/etc/nginx/certs/server.cert:ro,z'
      - './docker/nginx/server.key:/etc/nginx/certs/server.key:ro,z'
    depends_on:
      - ltb
      - latex-server
    ports:
      - '10443:443'
    networks:
      - ltb-network

  db:
    image: mariadb:10.11.16
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    restart: always
    environment:
      MYSQL_USER: ltb
      MYSQL_DATABASE: ltb
    env_file:
      - docker/db.env
    volumes:
      - 'ltb-database:/var/lib/mysql:z'
    ports:
      - '13306:3306'
    networks:
      - ltb-network

volumes:
  ltb-database:
  ltb-uploads:
  ltb-public:

networks:
  ltb-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.8.0/24
